version: '3'

services:
  caddy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/data/www:/www
      - /mnt/data/config:/config
    command: --conf /config/Caddyfile
