version: '3'

services:
  caddy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/data/www:/www
      - /mnt/data/config:/config
    command: --conf /config/Caddyfile
    restart: always
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - /mnt/data/openvpn:/etc/openvpn

